### ISSUE TITLE
Proxy issue?

### ISSUE THREAD

**Issue by fremgenc** [Mila432/Pokemon_Go_API#4]
I'm not sure if this is an issue only with me,  but I cannot get past this:

```
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\Pokemon_Go_API-master\main.py", line 47, in <module>
    main()
  File "C:\Users\admin\Desktop\Pokemon_Go_API-master\main.py", line 33, in main
    google_data= login.login_google('user@gmail.com','password')
  File "C:\Users\admin\Desktop\Pokemon_Go_API-master\login.py", line 38, in login_google
    r=config.s.get(first)
  File "c:\Python27\lib\site-packages\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "c:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "c:\Python27\lib\site-packages\requests\adapters.py", line 465, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/auth?client_id=848232511240-73ri3t7plvk96pj4f85uj8otdat2alem.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=openid%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 404 Not Found',)))
```

**Comment by Mila432** [comment]
It seems like you are trying to access HTTPS from google without a valid certificate. When using a custom signed , add it to the trust zone.

**Comment by Mila432** [comment]
Try this commit https://github.com/Mila432/Pokemon_Go_API/commit/398cf8aff39bf2befdb9abce091ad1c3a6ea3587
