### ISSUE TITLE
Google login issue - main.py

### ISSUE THREAD

**Issue by mikeres0** [Mila432/Pokemon_Go_API#52]
I am getting the following error from the `login.py` file when the `login_google` method is called from `main.py`:

`[!] Using google as login..
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    main()
  File "main.py", line 63, in main
    access_token,ltype=get_acces_token(args.username,args.password,args.type.lower())
  File "main.py", line 32, in get_acces_token
    google_data= login.login_google(usr,pws)
  File "/home/mikeres0/pokemongo-python/login.py", line 100, in login_google
    client_id= re.sub('.*_id=','',client_id.group(0))
AttributeError: 'NoneType' object has no attribute 'group'
`

Any ideas what could be going on here?

**Comment by RockFridrich** [comment]
Has the same problem

**Comment by mikeres0** [comment]
Now getting this message, I have just done a pull: `
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    main()
  File "main.py", line 66, in main
    access_token,ltype=get_acces_token(args.username,args.password,args.type.lower())
  File "main.py", line 37, in get_acces_token
    access_token= login.login_google_v2(usr,pws)
  File "/home/mikeres0/pokemongo-python/login.py", line 44, in login_google_v2
    r1 = perform_master_login(email, passw, AID)
NameError: global name 'perform_master_login' is not defined
`

**Comment by Mila432** [comment]
@mikeres0 https://github.com/Mila432/Pokemon_Go_API#requirements

**Comment by mikeres0** [comment]
@Mila432 I was just about to close this... I had spotted my stupid mistake. Thanks.
