### ISSUE TITLE
C'ant login with google in Ubuntu 16.04

### ISSUE THREAD

**Issue by qfdk** [Mila432/Pokemon_Go_API#76]
Thank you for all your hard work, i tried this command in ubuntu 16.04 with python 2.7

```bash
python main.py -u xxx@gmail.com -p xxxxx -l "home" -t google
```

I got this log

```
[!] Using google as login..
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    main()
  File "main.py", line 67, in main
    access_token,ltype=get_acces_token(args.username,args.password,args.type.lower())
  File "main.py", line 37, in get_acces_token
    access_token=google_data['id_token']
TypeError: string indices must be integers
```
I tried `print ` google_data 

it likes that 
```
eyJhbGciOiJSUzI1NiIsImtpZCI6IjRkODMzY2U0ODQzZTJlMTA0Y2FiNjkwNzFkZTg3Y2M3ZDc5NThhNjAifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiODQ4MjMyNTExMjQwLTdzbzQyMWpvdHIyNjA5cm1xYWtjZXV1MWx1dXEwcHRiLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTA0NzA3NDA3Nzk0NDYzMjkzNzY5IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6Ijg0ODIzMjUxMTI0MC0zdmRydHJmZG50bGpmMnU0bWxndG5ubGhuaWduMzVkNS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImVtYWlsIjoicWZkazIwMTFAZ21haWwuY29tIiwiaWF0IjoxNDY4OTMwMDYxLCJleHAiOjE0Njg5MzM2NjF9.vTtX8r58k5hr36x9BHUF6OKv
```

**Comment by qfdk** [comment]
that is token :) thx
